name: CI
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'yarn'
    - run: yarn install --immutable
    - name: Run ESLint
      run: yarn lint
    
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'yarn'
    - run: yarn install --immutable
    - run: xvfb-run -a yarn test
      if: runner.os == 'Linux'
    - run: yarn test
      if: runner.os != 'Linux'
