name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: elixir-tools

      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}


      - name: Install Node.js
        uses: actions/setup-node@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn install --immutable

      - name: publish to marketplace
        if: ${{ steps.release.outputs.release_created }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx vsce publish
